plugins/tff_backend/api/global_stats.py, plugins/tff_backend/api/investor.py, plugins/tff_backend/api/nodes.py, plugins/tff_backend/api/rogerthat/referrals.py, plugins/tff_backend/bizz/authentication.py, plugins/tff_backend/bizz/hoster.py, plugins/tff_backend/bizz/user.py
Get rid of 'users' suborganization.
=> Update iyo organizations

client/components/orders/order-detail.component.html, client/components/orders/order-list.component.html, client/interfaces/nodes.interfaces.ts, i18n/en.json, plugins/tff_backend/bizz/hoster.py, plugins/tff_backend/bizz/rogerthat.py, plugins/tff_backend/models/hoster.py, plugins/tff_backend/to/investor.py, plugins/tff_backend/to/iyo/keystore.py, plugins/tff_backend/to/iyo/see.py, plugins/tff_backend/to/iyo/user.py, plugins/tff_backend/to/nodes.py, plugins/tff_backend/utils/app.py
=> refactor(node-orders): Refactor node order flow to have separate billing and shipping info

plugins/tff_backend/bizz/hoster.py, plugins/tff_backend/bizz/investor.py
=> Payment instructions

client/components/investment-agreements/investment-agreement-detail-page.component.ts, client/interfaces/permissions.interfaces.ts, plugins/tff_backend/api/global_stats.py, plugins/tff_backend/api/investor.py, plugins/tff_backend/api/nodes.py, plugins/tff_backend/bizz/authentication.py, plugins/tff_backend/bizz/hoster.py, plugins/tff_backend/bizz/investor.py, plugins/tff_backend/tff_backend_plugin.py
After merging, remove these unneeded organization on itsyou.online:
- payment-admins
- investors
- hosters
- ambassadors
=> Update IYO organizations.

plugins/tff_backend/bizz/payment.py
Related to https://github.com/threefoldfoundation/transaction_log_backend/pull/1
=> Separate tierion and git backup

client/components/investment-agreements/investment-agreement-detail.component.html, client/components/investment-agreements/investment-agreement-list.component.html, client/interfaces/investment-agreements.interfaces.ts, i18n/en.json, plugins/tff_backend/bizz/investor.py, plugins/tff_backend/models/investor.py, plugins/tff_backend/to/investor.py
=> Add reference to investment agreements

client/components/orders/order-detail.component.html, client/components/orders/order-detail.component.ts, client/components/orders/order-list.component.ts, client/interfaces/nodes.interfaces.ts, client/scss/global.scss, i18n/en.json, plugins/tff_backend/bizz/hoster.py, plugins/tff_backend/bizz/odoo.py, plugins/tff_backend/models/hoster.py
Also adds a 'mark as paid' button to node orders and additional checks on backend
=> Add expiration date on Odoo quotations

client/components/investment-agreements/investment-agreement-detail-page.component.ts
=> fix(investments): Avoid doing unnecessary api call to get global stats

client/operators.ts, plugins/tff_backend/bizz/intercom_helpers.py, plugins/tff_backend/bizz/investor.py, plugins/tff_backend/bizz/iyo/utils.py, plugins/tff_backend/dal/investment_agreements.py, plugins/tff_backend/dal/node_orders.py, plugins/tff_backend/handlers/cron.py, plugins/tff_backend/migrations/_002_intercom_tags.py, plugins/tff_backend/models/hoster.py, plugins/tff_backend/models/investor.py
Migration:
```python
def iyo_2():
from plugins.its_you_online_auth.migrations._002_profile_pointers import migrate
return migrate(dry_run=False)
```
=> fix: Add mapping between username and app user

brandings/livechat/cordova.html, plugins/tff_backend/bizz/user.py
See https://github.com/rogerthat-platform/plugin-intercom-support/pull/7 as well
=> Re-use same conversation for live chat

client/components/api-request-status.component.ts, client/components/orders/order-detail-page.component.ts, client/services/api-error.service.ts, client/services/index.ts, i18n/en.json, plugins/tff_backend/bizz/hoster.py, plugins/tff_backend/bizz/nodes.py
=> fix(node-orders): check if node order has a serial number on odoo before allowing marking a node order as send

plugins/tff_backend/bizz/hoster.py, plugins/tff_backend/dal/investment_agreements.py, plugins/tff_backend/dal/node_orders.py, plugins/tff_backend/migrations/_004_hoster_status_in_user_data.py, plugins/tff_backend/models/hoster.py, plugins/tff_backend/utils/search.py
updated flow available on staging
=> fix(node-orders): Only allow one node order per user and per address

plugins/tff_backend/bizz/global_stats.py, plugins/tff_backend/configuration.py, plugins/tff_backend/plugin_consts.py, plugins/tff_backend/to/global_stats.py
=> fix(global-stats): Change api used to get realtime currency conversion

plugins/tff_backend/bizz/investor.py, plugins/tff_backend/bizz/todo/investor.py, plugins/tff_backend/migrations/_006_investor_todo_list.py
```python
def tff_006_investor_todo_list():
from plugins.tff_backend.migrations._006_investor_todo_list import migrate
return migrate(True)
```
run `migrate(False)` to execute for real, else it's a dry run which returns the users which will be updated
=> Update investor todo list

plugins/tff_backend/api/rogerthat/referrals.py, plugins/tff_backend/bizz/kyc/rogerthat_callbacks.py
=> Set referral during KYC flow

client/components/investment-agreements/investment-agreement-detail-page.component.ts, client/interfaces/permissions.interfaces.ts, plugins/tff_backend/api/agenda.py, plugins/tff_backend/api/audit.py, plugins/tff_backend/api/global_stats.py, plugins/tff_backend/api/investor.py, plugins/tff_backend/api/nodes.py, plugins/tff_backend/api/rogerthat/referrals.py, plugins/tff_backend/api/users.py, plugins/tff_backend/bizz/authentication.py, plugins/tff_backend/bizz/hoster.py, plugins/tff_backend/bizz/investor.py, plugins/tff_backend/bizz/service.py, plugins/tff_backend/bizz/user.py, plugins/tff_backend/migrations/_007_referral_in_user_data.py, plugins/tff_backend/rogerthat_callbacks.py, plugins/tff_backend/tff_backend_plugin.py
Closes #241 
Closes #238 
[kyc_part_1.json](https://github.com/threefoldfoundation/app_backend/files/1575145/kyc_part_1.txt)
=> Change permissions and make referral optional in KYC flow

i18n/en.json, plugins/tff_backend/bizz/rogerthat.py, plugins/tff_backend/bizz/user.py
=> feat(kyc): Send message after user has been KYC approved

client/components/kyc/kyc.component.ts, i18n/en.json, plugins/tff_backend/bizz/user.py
Updated flow (moved 'vibrate' step to 1st step, and only show that step when flow param 'message' is set):
```json
{"modules":[{"config":{"position":[47,17]},"name":"Start","value":{}},{"config":{"position":[5,1128]},"name":"End","value":{"id":"end","waitForFollowUpMessage":true}},{"config":{"formMessageDef":{"attachments_group":{"attachments_list":[]},"choices_group":{"choices_list":[{"label":"British","value":"GB"},{"label":"Belgian","value":"BE"}]},"form_settings_group":{"button-editor-name-f64ac0d3-61e8-7ead-95f7-6daf2f9c8f77":"","javascript_validation":"","negative_caption":"Cancel","negative_confirmation":"","positive_caption":"Submit","positive_confirmation":"","value":""},"id":"nationality","message":"What is your nationality?","message_settings_group":{"alert_interval":"NONE","ale …
```
=> feat(kyc): Show message before KYC flow when resending KYC flow

client/actions/threefold.action.ts, client/components/monitoring/dashboard.component.css, client/components/monitoring/dashboard.component.html, client/components/monitoring/dashboard.component.ts, client/components/monitoring/installation.component.html, client/interfaces/dashboard.ts, client/interfaces/flow-statistics.interfaces.ts, client/interfaces/index.ts, client/package.json, client/pages/monitoring/dashboard-page.component.ts, client/routes/index.ts, client/routes/node-order-routes.ts, client/services/tff.service.ts, client/states/tff.state.ts, client/tff-backend.module.ts, i18n/en.json, plugins/cron.yaml, plugins/tff_backend/api/flow_statistics.py, plugins/tff_backend/bizz/dashboard.py, plugins/tff_backend/bizz/flow_statistics.py, plugins/tff_backend/bizz/installations.py, plugins/tff_backend/bizz/user.py, plugins/tff_backend/firebase.py, plugins/tff_backend/handlers/cron.py, plugins/tff_backend/rogerthat_callbacks.py, plugins/tff_backend/tff_backend_plugin.py, plugins/tff_backend/to/dashboard.py
Also improves the data structure behind it to be more realtime
Currently live on staging
=> feat(dashboard): Improve dashboard by using pie charts

client/components/monitoring/dashboard.component.ts, client/pages/monitoring/dashboard-page.component.html, client/pages/monitoring/dashboard-page.component.ts, plugins/tff_backend/bizz/investor.py, plugins/tff_backend/consts/kyc.py, plugins/tff_backend/migrations/_010_create_token_value_agreement.py, plugins/tff_backend/models/document.py, plugins/tff_backend/models/investor.py, plugins/tff_backend/plugin_consts.py
=> Add migration for token value agreements

plugins/tff_backend/bizz/nodes/stats.py
=> refactor(nodes): Run checking node status in batches to reduce amount of requests
